{% set name = "chilife" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chilife-{{ version }}.tar.gz
  sha256: 768e2c0a5186b7dab02f044b8a4de56d79cacb6bbc00dd677bd2b0c90b72cf1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - matplotlib-base
    - wheel
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.23.0,<2.0
    - scipy >=1.6.3
    - matplotlib-base >=3.3.4
    - numba >=0.57.0
    - mdanalysis >=2.0.0
    - tqdm >=4.45.0
    - pytest >=6.2.2
    - memoization >=0.3.1
    - python-igraph >=0.10.3
    - rtoml >=0.9.0,<0.10

test:
  imports:
    - chilife
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A package for modeling non-canonical amino acid side chain ensembles.
  home: https://github.com/stollLab/chiLife/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtessmer
